In [1]:
import numpy as np
import pandas as pd

In [47]:
df_train = pd.read_csv('./training_data.csv')
df_validate = pd.read_csv('./validation_data.csv')

In [48]:
Y = df_train.iloc[:,-1]

In [49]:
X = df_train.iloc[:,:40]

In [50]:
Y = np.asarray(Y)
X = np.asarray(X)

In [51]:
df_train.head()

,Feature0,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,...,Feature31,Feature32,Feature33,Feature34,Feature35,Feature36,Feature37,Feature38,Feature39,Y
0,0.140514,-0.533037,1.478885,-0.050549,0.504151,-0.440043,1.812464,-0.095540,0.891967,1.617159,...,-1.872650,-0.135790,0.091042,0.566925,-0.219366,0.569566,0.547480,0.097368,0.123405,1.342829
1,-0.898200,-0.782070,0.108701,1.364893,0.593578,-0.902526,-0.082300,1.179372,-0.518053,-0.225826,...,-1.288518,-0.180014,0.859563,0.124860,-0.250582,-0.700927,0.482043,-0.206814,1.202387,0.876341
2,-0.813415,0.344493,1.595646,-0.145575,1.291868,0.029102,-1.304461,0.737832,0.087635,0.443799,...,-1.022622,2.265219,0.391877,0.042783,1.893751,-0.432940,-0.703125,0.866596,-0.529517,1.827752
3,-1.375832,-1.649615,-0.042596,-1.084870,-0.608164,0.817495,0.297666,-0.346243,-0.533978,1.122233,...,-0.203589,0.235016,-0.290859,-0.180092,-0.299549,0.512530,-0.955217,1.774759,0.684536,1.841433
4,-1.046623,0.965945,-0.326887,0.165514,0.109975,0.874498,1.197480,-0.201127,0.230544,-0.743749,...,0.079365,-0.347910,0.771725,0.368069,1.173361,-0.895052,0.704253,-0.585195,1.094100,1.728270

In [52]:
df_validate.head()

,Feature0,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,...,Feature31,Feature32,Feature33,Feature34,Feature35,Feature36,Feature37,Feature38,Feature39,Y
0,2.514067,1.241701,0.265190,-1.091046,0.210098,-1.497203,0.384481,-0.071802,-0.431148,-0.060410,...,0.470286,-0.881884,0.314778,-1.660699,-2.008732,0.085190,-0.370010,1.807763,-0.049346,1.793858
1,-1.654812,-0.653405,0.627753,-0.866637,-0.129803,1.066956,1.402694,-1.311003,0.271153,0.632560,...,-0.764462,1.033862,-0.323576,-0.959513,0.718359,-0.100014,-1.215583,-1.080602,-0.692482,0.860383
2,-0.692665,0.209629,0.726088,0.182588,-1.603156,0.539350,0.068681,0.366434,-0.343775,-0.738347,...,-1.020515,-1.058291,-0.513445,0.149978,0.751203,0.652588,2.917279,-1.508049,-0.460500,0.905793
3,-0.811152,1.120494,-1.673626,-1.058446,-0.112530,0.127502,1.442720,0.112246,0.313139,0.558230,...,-1.732976,-0.050600,-2.061478,0.010916,0.029728,0.150107,0.657595,1.487340,-1.440906,0.847834
4,0.779609,0.822661,-0.033176,0.352609,0.033452,-1.057172,-0.550528,-0.689131,1.489944,-2.288066,...,1.407897,1.327041,-1.807242,-0.164339,-0.211571,-1.055292,-1.439126,0.043110,-0.343585,0.855014

In [53]:
print(df_train.shape)
print(df_validate.shape)

(800, 41)
(200, 41)

In [54]:
def sigmoid(w,x):
    return 1/(1+np.exp(-(w*x)))

def error(w):
    err = 0
    for x,y in zip(X,Y):
        fx = sigmoid(w,x)
        err = err+0.5*(fx-y)**2
    return err

In [55]:
w = np.load('weights_after_epoch_0.npy')
err = error(w)

In [56]:
w

array([[ 0.25008539,  0.70445457,  0.1587082 ,  0.43054321,  0.26483861,
         0.43260431,  0.21702123,  0.40871228,  0.94455534,  0.53837901,
         0.78661373,  0.54700948,  0.33305398,  0.67703856,  0.03145958,
        -0.11449891, -0.60665718,  0.79129729,  0.96109767,  0.55657989,
         0.95023645,  0.09521403,  0.37170334,  0.18322878, -0.17092661,
         0.47852233, -0.28740263,  0.65447856,  0.45093357,  0.34838723,
         0.3010536 ,  0.11006918,  0.45655649,  0.6861629 ,  0.0277843 ,
         0.57139552,  0.8376329 ,  0.75700116,  0.98963601,  0.37779808]])

In [57]:
print(err)

[[356.07149913 356.55523747 356.2787462  355.29555918 356.19713554
  356.01492535 356.77349479 357.19940034 355.29853263 358.33851114
  358.11869302 356.5662299  355.74643986 357.52780931 356.65159762
  357.14723987 357.99401498 356.80303239 353.18510029 357.62645766
  356.66598003 356.90453035 354.82633926 356.97181726 356.66782129
  356.99098226 357.0249854  354.13317064 354.95362756 356.7618241
  356.22103622 356.63951347 356.63106767 357.12830036 356.81694315
  356.18792216 353.80584013 355.85191495 351.46624521 355.71347046]]

In [2]:
w = np.load('weights_after_epoch_1.npy')

In [36]:
print(error(w))

[[356.24449815 356.30635531 357.06667725 356.53773344 356.03607357
  356.79758285 358.22935262 356.96108397 357.37871885 356.39269435
  357.02908105 355.15036142 356.30445954 356.38606303 356.76080462
  356.70494161 356.83629375 355.13839254 352.03813768 357.10880855
  357.20091644 358.93597184 357.7259343  358.26978948 356.67338193
  355.61459452 356.49061128 356.41313879 355.09422052 357.7859832
  357.44314631 356.97533585 356.49338042 357.49675224 356.88545711
  355.69913522 353.55027184 355.24512141 352.50290621 357.85039113]]

In [37]:
w = np.load('weights_after_epoch_2.npy')

In [38]:
print(error(w))

[[356.32304865 357.0658948  357.63551167 356.74435773 356.08739715
  357.45002513 358.69699834 357.0625405  357.39702922 356.46389817
  356.93808282 355.10776702 356.1598492  356.79981436 356.86084933
  356.69519515 357.06120474 355.8654034  351.97803868 356.85352774
  358.08832423 361.13061799 357.99596386 359.19820559 356.62123658
  355.88182144 356.53937035 356.77768823 355.59247809 358.79036482
  356.81046409 357.7718109  356.24587408 357.89209388 356.76469717
  355.98600242 353.2296923  355.15219837 352.48743013 357.59239965]]

In [39]:
w = np.load('weights_after_epoch_3.npy')

In [40]:
print(error(w))

[[356.33879251 357.34230097 357.85773873 357.02373661 356.05127753
  358.11049024 359.59624081 357.31864531 358.59232793 356.73080856
  356.82615293 355.01212161 356.21891178 356.81936178 357.00948512
  356.71194408 357.10072689 356.12010505 351.91909396 357.0761728
  358.46678249 362.12627956 358.75493962 359.77365634 356.53631954
  356.03094251 356.4070115  356.96163868 355.78522086 359.43229302
  356.56657365 358.36005193 356.04513005 358.18249885 356.86921721
  356.60543536 353.03045126 355.28831303 352.73379093 358.1537756 ]]

In [41]:
w = np.load('weights_after_epoch_4.npy')

In [42]:
print(error(w))

[[356.30658927 357.76443887 358.12566924 357.21112547 356.08091862
  358.54115014 360.32167075 357.65827233 359.23420422 356.8352728
  356.71042086 355.04522973 356.29487453 357.08504888 357.11984804
  356.75161137 357.2088927  356.4230906  352.05091103 357.21611952
  359.10228562 363.44451838 359.04132975 360.39795576 356.51091447
  356.21301323 356.46922541 357.31461798 356.03183114 360.25605542
  356.34797038 359.02693398 355.96217045 358.78549857 356.79080708
  357.14747601 353.00443287 355.45874362 352.68026923 358.42428902]]